USE [master]
GO
/****** Object:  Database [FindFriends]    Script Date: 11/05/2018 05:38:08 ******/
CREATE DATABASE [FindFriends]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FindFriends', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\FindFriends.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FindFriends_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\FindFriends_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [FindFriends] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FindFriends].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FindFriends] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FindFriends] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FindFriends] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FindFriends] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FindFriends] SET ARITHABORT OFF 
GO
ALTER DATABASE [FindFriends] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FindFriends] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FindFriends] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FindFriends] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FindFriends] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FindFriends] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FindFriends] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FindFriends] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FindFriends] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FindFriends] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FindFriends] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FindFriends] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FindFriends] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FindFriends] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FindFriends] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FindFriends] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FindFriends] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FindFriends] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FindFriends] SET  MULTI_USER 
GO
ALTER DATABASE [FindFriends] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FindFriends] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FindFriends] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FindFriends] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FindFriends] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FindFriends] SET QUERY_STORE = OFF
GO
USE [FindFriends]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [FindFriends]
GO
/****** Object:  Table [dbo].[CalculateLog]    Script Date: 11/05/2018 05:38:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CalculateLog](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SearchNumber] [int] NOT NULL,
	[BaseFriendName] [varchar](50) NULL,
	[NearbyFriendName] [varchar](50) NULL,
	[Rank] [int] NULL,
	[Created] [datetime2](7) NULL,
 CONSTRAINT [PK_CalculateLog] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Friends]    Script Date: 11/05/2018 05:38:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Friends](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[City] [varchar](40) NULL,
	[Country] [varchar](25) NULL,
	[Latitude] [decimal](10, 4) NULL,
	[Longitude] [decimal](10, 4) NULL,
 CONSTRAINT [PK_Friends] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [idx_Name]    Script Date: 11/05/2018 05:38:09 ******/
CREATE NONCLUSTERED INDEX [idx_Name] ON [dbo].[Friends]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [FindFriends] SET  READ_WRITE 
GO
